### ISSUE TITLE
About Search

### ISSUE THREAD

**Issue by bxyster** [rji/waylon#73]
I 'd like to search All Jenkins Server from api using waylon, for example, project/branch etc, how do I realize it.  I can do some logic in waylon.rb,  like collecting all jobs storing in the array variable below

-------------------------------------------------------------------------
    get_views().each do |each_view|
      manadic(Either.attempt_all(self) do
         try { Waylon::Jenkins.view(gen_config, each_view) }
         try { |view| all_jobs += view.jobs }
      end)
    end
-------------------------------------------------------------------------

And then  reformat the array to get the value I need,  But I it's not as elegant as I want, It's better to change the route in lib/waylon/jenkins.rb or backbone view model . 

Can give some advice or help?  Thanks very much~

**Comment by rji** [comment]
Waylon has an undocumented REST API that you might find helpful. (The documentation work is ticketed as #66 but I just haven't gotten around to it yet.)

If I understand your use-case correctly, you should be able to create a single Waylon view (let's name it "All Jobs") that contains all of your Jenkins servers, and references the Jenkins built-in view "All". The configuration might look like this.

```yaml
views:
  'All Jobs':
    jenkins1:
      url: https://jenkins1.example.com
      username: 'waylon'
      password: 'topsecretpw'
      views:
        - 'All'
      jenkins2:
        url: https://jenkins2.example.com
        username: 'waylon'
        password: 'topsecretpw'
        views:
          - 'All'
```
... etc.

You could then hit the endpoint `/api/view/All%20Jobs/jobs.json` (implemented [here](https://github.com/rji/waylon/blob/acaf03197e593e57ceb7f9406d03377f26a1edb2/waylon.rb#L98-L108)) to get a list of all of the jobs for that particular view, which would be all the jobs on all the Jenkins instances in the list.

I'm not sure how many jobs or Jenkins instances you have, so just a word of caution: Waylon was designed to display a small number of jobs for various development teams. In some cases, we have it querying for – and displaying – around 200 jobs per view without a problem. If you go too much over this, you might want to consider reconfiguring `refresh_interval` in waylon.yml, so that the requests don't start to pile up.

Alternately, you could use the jenkins_api_client gem in your application directly: https://github.com/arangamani/jenkins_api_client

I hope that helps.
